document.addEventListener("DOMContentLoaded", function () {
  const topicInput = document.getElementById("topicInput");
  const generateBtn = document.getElementById("generateBtn");
  const resultsContainer = document.getElementById("resultsContainer");
  const loadingModal = document.getElementById("loadingModal");
  const apiInfoModal = document.getElementById("apiInfoModal");
  const topicChips = document.querySelectorAll(".topic-chip");

  let currentStep = 0;

  // Handle example topic chips
  topicChips.forEach((chip) => {
    chip.addEventListener("click", function () {
      topicInput.value = this.textContent;
    });
  });

  // Handle Enter key in input
  topicInput.addEventListener("keypress", function (e) {
    if (e.key === "Enter" && !generateBtn.disabled) {
      generateHeadline();
    }
  });

  // Handle generate button click
  generateBtn.addEventListener("click", generateHeadline);

  async function generateHeadline() {
    const topic = topicInput.value.trim();

    if (!topic) {
      showError("Please enter a topic");
      return;
    }

    // Disable button and show loading
    generateBtn.disabled = true;
    generateBtn.innerHTML =
      '<i class="fas fa-spinner fa-spin"></i><span>Generating...</span>';

    // Show loading modal with step animation
    showLoadingModal();

    try {
      const response = await fetch("/api/generate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ topic }),
      });

      const data = await response.json();

      // Simulate agent steps (for UI effect)
      simulateAgentSteps(() => {
        hideLoadingModal();
        displayResult(data, topic);
      });
    } catch (error) {
      hideLoadingModal();
      showError("Network error. Please try again.");
    } finally {
      generateBtn.disabled = false;
      generateBtn.innerHTML =
        '<i class="fas fa-bolt"></i><span>Generate Headline</span>';
    }
  }

  function showLoadingModal() {
    loadingModal.style.display = "block";
    startStepAnimation();
  }

  function hideLoadingModal() {
    loadingModal.style.display = "none";
    currentStep = 0;
    updateAgentSteps();
  }

  function startStepAnimation() {
    const steps = document.querySelectorAll(".agent-step");
    steps.forEach((step) => step.classList.remove("active"));

    const interval = setInterval(() => {
      if (currentStep < steps.length) {
        steps[currentStep].classList.add("active");
        currentStep++;
      } else {
        clearInterval(interval);
      }
    }, 1000);
  }

  function simulateAgentSteps(callback) {
    setTimeout(callback, 4000); // Simulate processing time
  }

  function displayResult(data, topic) {
    const resultHTML = data.success
      ? createSuccessHTML(data, topic)
      : createErrorHTML(data);

    resultsContainer.innerHTML = resultHTML;
    resultsContainer.scrollIntoView({ behavior: "smooth" });
  }

  function createSuccessHTML(data, topic) {
    const date = new Date().toLocaleDateString("en-US", {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    const time = new Date().toLocaleTimeString("en-US", {
      hour: "2-digit",
      minute: "2-digit",
    });

    return `
            <div class="headline-result">
                <div class="headline-topic">
                    <i class="fas fa-tag"></i>
                    <h3>Topic: ${topic}</h3>
                    <span class="status-badge status-success">
                        <i class="fas fa-check-circle"></i>
                        Generated Successfully
                    </span>
                </div>
                <div class="headline-content">
                    <div class="headline-text">${data.headline}</div>
                    <div class="result-meta">
                        <span><i class="far fa-calendar"></i> ${date}</span>
                        <span><i class="far fa-clock"></i> ${time}</span>
                        <span><i class="fas fa-save"></i> Saved to Google Sheets</span>
                    </div>
                </div>
                <p style="color: var(--text-secondary); font-size: 0.9rem;">
                    <i class="fas fa-info-circle"></i> This headline was generated by the AI agent and saved to your spreadsheet.
                </p>
            </div>
        `;
  }

  function createErrorHTML(data) {
    return `
            <div class="headline-result">
                <div class="headline-topic">
                    <i class="fas fa-exclamation-triangle"></i>
                    <h3>Generation Failed</h3>
                    <span class="status-badge status-error">
                        <i class="fas fa-times-circle"></i>
                        Error Occurred
                    </span>
                </div>
                <div class="headline-content">
                    <p style="color: var(--error);">${
                      data.error || "Unknown error occurred"
                    }</p>
                </div>
                <p style="color: var(--text-secondary); font-size: 0.9rem;">
                    <i class="fas fa-lightbulb"></i> Please check your API keys and try again.
                </p>
            </div>
        `;
  }

  function showError(message) {
    const errorHTML = `
            <div class="headline-result">
                <div class="headline-content">
                    <p style="color: var(--error); text-align: center;">
                        <i class="fas fa-exclamation-circle"></i> ${message}
                    </p>
                </div>
            </div>
        `;
    resultsContainer.innerHTML = errorHTML;
  }

  // Modal functions
  window.showApiInfo = function () {
    apiInfoModal.style.display = "block";
  };

  window.showCredits = function () {
    alert(
      "Built with:\n• CrewAI Framework\n• Google Gemini AI\n• Groq AI\n• Serper API\n• Google Sheets API"
    );
  };

  window.closeModal = function () {
    apiInfoModal.style.display = "none";
  };

  // Close modals when clicking outside
  window.onclick = function (event) {
    if (event.target === loadingModal || event.target === apiInfoModal) {
      event.target.style.display = "none";
    }
  };

  // Initialize empty state
  resultsContainer.innerHTML = `
        <div class="empty-state">
            <i class="fas fa-headline"></i>
            <h3>No Headlines Yet</h3>
            <p>Enter a topic above to generate your first headline!</p>
        </div>
    `;
});
